/**
 * Tiny cream-tinted JPEG used as a blur placeholder while Supabase
 * images stream in. 4×4 px, ~150 bytes — ships in the HTML payload so
 * the user sees something the moment markup paints, instead of an
 * empty grey box waiting for /_next/image to finish.
 */
export const BLUR_DATA_URL =
  'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/2wCEABALCwsMCwwMDAwMDhANEA4UEhAQEhQfFRYVFhUfMR0gHR0gHTEqMygnKDMqRDQwMDREVURPVURPYV1hYXOAcICfn8//2wCEARALCwsMCwwMDAwMDhANEA4UEhAQEhQfFRYVFhUfMR0gHR0gHTEqMygnKDMqRDQwMDREVURPVURPYV1hYXOAcICfn8//wgARCAAEAAQDAREAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAEDB//EABYBAQEBAAAAAAAAAAAAAAAAAAACA//aAAwDAQACEAMQAAABKr6P/8QAFRAAAQAAAAAAAAAAAAAAAAAAACD/2gAIAQEAAQUCDz//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AT//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/AT//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAY/Aj//xAAVEAEBAAAAAAAAAAAAAAAAAAABMP/aAAgBAQABPyEh/9oADAMBAAIAAwAAABCD/wD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/ED//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/ED//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/EBP/2Q==';
